<div className="mt-2 space-y-2">
              <div className="flex flex-wrap gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadKhiFormatSample}
                >
                  KHI格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadSampleData}
                >
                  传统格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadNewFormatSample}
                >
                  批量格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadLatestFormatSample}
                >
                  单托格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadTableFormatSample}
                >
                  表格格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadBoxFormatSample}
                >
                  箱规格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadCommFormatSample}
                >
                  商品格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadPalletFormatSample}
                >
                  托盘格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadMultiSizeFormatSample}
                >
                  多尺寸格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadAirFormatSample}
                >
                  空运格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadMoreAirportSample}
                >
                  更多机场代码示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadBoxSample}
                >
                  木箱格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadElectricSample}
                >
                  带电货物示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadBatterySample}
                >
                  电池类示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadGeneralCargoSample}
                >
                  普通货物示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadBoxCountSample}
                >
                  箱数格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadComplexFormatSample}
                >
                  复杂格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadSingleItemSpecSample}
                >
                  单件规格示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadChineseVolumeSample}
                >
                  中文体积示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadLedProductSample}
                >
                  LED产品示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadQuestionMarkSample}
                >
                  问号字符修复示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadWeightVolumePiecesSample}
                >
                  重量/体积/件数格式
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadFlexibleOrderSample}
                >
                  智能顺序识别
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadPalletDetailSample}
                >
                  托盘详细格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadDelTripleSample}
                >
                  DEL三元组示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadTripleFormat1}
                >
                  三元组格式1
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadTripleFormat2}
                >
                  三元组格式2
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadTripleFormat3}
                >
                  三元组格式3
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadTripleFormat4}
                >
                  三元组格式4
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadTripleFormat5}
                >
                  三元组格式5
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadCtnsFormatSample}
                >
                  CTNS格式+箱规示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadCcuFormatSample}
                >
                  CCU新格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadKhiDoubleSlashFormatSample}
                >
                  KHI双斜杠格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadBegFormatSample}
                >
                  BEG新格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadPekFormatSample}
                >
                  PEK新格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadSimpleTripleFormatSample}
                >
                  简化三元组格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadBomFormatSample}
                >
                  BOM新格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadGwFormatSample}
                >
                  GW格式示例
                </Button>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={loadNwFormatSample}
                >
                  NW格式示例
                </Button>
              </div>
            </div>
